--CREATE SNOWPIPE THAT RECOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO EXISTING TABLE

--The AUTO_INGEST=true parameter specifies to read 
--- event notifications sent from an S3 bucket to an SQS queue when new data is ready to load.



CREATE OR REPLACE PIPE RETAIL_DEMOGRAPHIC AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.DEMOGRAPHIC_RAW
FROM '@RETAIL/demographic/'
FILE_FORMAT = retail_csv;


CREATE OR REPLACE PIPE RETAIL_CAMPAIGN_DESC AUTO_INGEST = TRUE AS
COPY INTO RETAILS.PUBLIC.CAMPAIGN_DESC_RAW
FROM '@RETAIL/campaign_desc/'
FILE_FORMAT = retail_csv;


CREATE OR REPLACE PIPE RETAIL_CAMPAIGN AUTO_INGEST = TRUE AS 
COPY INTO RETAILS.PUBLIC.CAMPAIGN_RAW
FROM '@RETAIL/campaign_raw/'
FILE_FORMAT = retail_csv;


CREATE OR REPLACE PIPE PRODUCT AUTO_INGEST = TRUE AS 
COPY INTO RETAILS.PUBLIC.PRODUCT_RAW
FROM '@RETAIL/product_raw/'
FILE_FORMAT = retail_csv;


CREATE OR REPLACE PIPE RETAIL_COUPON AUTO_INGEST = TRUE AS 
COPY INTO RETAILS.PUBLIC.COUPON_RAW
FROM '@RETAIL/coupon_raw/'
FILE_FORMAT = retail_csv;


CREATE OR REPLACE PIPE RETAIL_COUPON_REDEMPT AUTO_INGEST = TRUE AS 
COPY INTO RETAILS.PUBLIC.COUPON_REDEMPT_RAW
FROM '@RETAIL/coupon_redempt_raw/'
FILE_FORMAT = retail_csv;



CREATE OR REPLACE PIPE RETAIL_TRANSACTION AUTO_INGEST = TRUE AS 
COPY INTO RETAILS.PUBLIC.TRANSACTION_RAW
FROM '@RETAIL/transaction_raw/'
FILE_FORMAT = retail_csv;

SHOW PIPES;


ALTER PIPE RETAIL_DEMOGRAPHIC REFRESH;
ALTER PIPE RETAIL_CAMPAIGN_DESC REFRESH;
ALTER PIPE RETAIL_CAMPAIGN REFRESH;
ALTER PIPE PRODUCT REFRESH;
ALTER PIPE RETAIL_COUPON REFRESH;
ALTER PIPE RETAIL_TRANSACTION REFRESH;



select count(*) from transaction_raw



